/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "error-container": "#ffdad6",
        "secondary": "#006a61",
        "surface-tint": "#006399",
        "error": "#ba1a1a",
        "surface-container-low": "#eff4ff",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#6bd8cb",
        "secondary-container": "#86f2e4",
        "surface-container": "#e5eeff",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#213145",
        "surface": "#f8f9ff",
        "surface-bright": "#f8f9ff",
        "on-primary-fixed": "#001d32",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#d3e4fe",
        "secondary-fixed": "#89f5e7",
        "inverse-primary": "#94ccff",
        "on-secondary-fixed-variant": "#005049",
        "on-secondary-container": "#006f66",
        "tertiary": "#3f4d61",
        "surface-variant": "#d3e4fe",
        "primary": "#00507d",
        "primary-fixed": "#cde5ff",
        "outline-variant": "#c0c7d1",
        "primary-fixed-dim": "#94ccff",
        "surface-container-high": "#dce9ff",
        "on-tertiary-container": "#d4e2fb",
        "on-error": "#ffffff",
        "on-surface-variant": "#40474f",
        "inverse-on-surface": "#eaf1ff",
        "on-primary-container": "#cbe4ff",
        "tertiary-fixed-dim": "#b9c7df",
        "primary-container": "#0369a1",
        "on-tertiary-fixed": "#0d1c2e",
        "on-tertiary-fixed-variant": "#3a485b",
        "on-surface": "#0b1c30",
        "background": "#f8f9ff",
        "outline": "#707881",
        "surface-dim": "#cbdbf5",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#00201d",
        "on-primary-fixed-variant": "#004b74",
        "on-primary": "#ffffff",
        "on-background": "#0b1c30",
        "tertiary-fixed": "#d5e3fc",
        "tertiary-container": "#57657a"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "margin-mobile": "1rem",
        "gutter-mobile": "1rem",
        "margin-tablet": "1.5rem",
        "space-2xl": "2.5rem",
        "space-lg": "1.5rem",
        "space-base": "1rem",
        "space-sm": "0.5rem",
        "space-xl": "2rem",
        "max-width-content": "1600px",
        "gutter-desktop": "1.5rem",
        "space-3xl": "3rem",
        "margin-desktop": "2rem",
        "space-2xs": "0.125rem",
        "space-md": "0.75rem",
        "space-xs": "0.25rem"
      },
      "fontFamily": {
        "label-lg": ["Inter"],
        "code-md": ["JetBrains Mono"],
        "headline-md": ["Hanken Grotesk"],
        "body-sm": ["Inter"],
        "headline-xl": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "headline-sm": ["Hanken Grotesk"],
        "display-lg": ["Hanken Grotesk"],
        "code-sm": ["JetBrains Mono"],
        "display-lg-mobile": ["Hanken Grotesk"],
        "label-sm": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "label-md": ["Inter"],
        "headline-xl-mobile": ["Hanken Grotesk"]
      },
      "fontSize": {
        "label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "code-md": ["13px", { "lineHeight": "18px", "fontWeight": "400" }],
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "body-sm": ["12px", { "lineHeight": "18px", "fontWeight": "400" }],
        "headline-xl": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-sm": ["16px", { "lineHeight": "24px", "fontWeight": "600" }],
        "display-lg": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "code-sm": ["11px", { "lineHeight": "16px", "fontWeight": "500" }],
        "display-lg-mobile": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.04em", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "headline-xl-mobile": ["26px", { "lineHeight": "34px", "letterSpacing": "-0.015em", "fontWeight": "600" }]
      }
    }
  },
  plugins: [],
}
